/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_asyf_app_jni_JniTest */

#ifndef _Included_com_asyf_app_jni_JniTest
#define _Included_com_asyf_app_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_asyf_app_jni_JniTest
 * Method:    getStrFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_asyf_app_jni_JniTest_getStrFromC
  (JNIEnv *,jclass,jobject);

#ifdef __cplusplus
}
#endif
#endif
